Add dynamic build version (semver) and git commit + date into the cli --version

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -17,12 +17,24 @@ if [ -z "$CMAKE_BUILD_TYPE" ]; then
   CMAKE_BUILD_TYPE=Debug
 fi
 
+export BUILD_REVISION=$(git rev-parse --short --verify HEAD)
+export BUILD_TIMESTAMP=$(date)
+
+if [[ "$BUILD_REVISION" == "" ]]; then
+  echo "Invalid Build Revision: $BUILD_REVISION"
+  exit 1
+fi
+
 echo
 echo -e " Building: $CMAKE_BUILD_TYPE"
+echo -e " BUILD_TIMESTAMP: $BUILD_TIMESTAMP"
+echo -e " BUILD_REVISION: $BUILD_REVISION "
 echo -e "-------------------------------------\n"
 
 if [[ ! -f $ROOT/build/Makefile ]]; then
-  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
+  cmake \
+    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
+    -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
   if [ ! $? -eq 0 ]; then
     exit 1
   fi
